spring.application.name=task-service
server.port=${SERVER_PORT:8083}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
