services:
  postgres:
    image: postgres:15
    container_name: crm_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: crm_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - crm_network

  employee-service:
    image: ghcr.io/lukac011/employee-service:latest
    container_name: crm_employee_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - crm_network
  prometheus:
    image: prom/prometheus
    container_name: crm_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - crm_network

  grafana:
    image: grafana/grafana
    container_name: crm_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - crm_network

volumes:
  pgdata:

networks:
  crm_network:
    driver: bridge
